### ISSUE TITLE
side effects of rate-limits (from Magnus)

### ISSUE THREAD

**Issue by boucadair** [boucadair/draft-ietf-lisp-pubsub#2]
> Also beyond rate limiting, is there a possibility here to reject the MAP-requests from a source address, without causing a denial of service attack possibility? My shallow review seem to indicate that there exist such a risk. What I am considering is that there is a legit xTR (B) with IP (IP-B). If the attacker sends a MAP-Request with nonce-A, with IP source address IP-B. The Map-Notify will go to B. B can’t map this to a request it made as no Nonce matches what it sends and discards the message. Thus, the map server getting a mix of legit and spoofed requests may decide to band IP-B from asking things, thus enabling a denial of service on B.

**Comment by boucadair** [comment]
For this attack to work, the spoofed request should include a valid xTR-ID and passes the authentication checks at the Map-Server.

An attacker who has access to the keys can do more harm.

**Comment by arnatal** [comment]
Technically the checks are passed at the Map-Resolver, who should verify the integrity and authenticity of the Map-Request, (and potentially to check if the xTR is allowed to subscribe).
